# Generated by Django 3.0.5 on 2020-05-24 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_connected', models.BooleanField(default=False)),
                ('miles', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10000, null=True)),
                ('community', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10000, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
