# Generated by Django 3.0.5 on 2020-05-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(default='True', max_length=254),
        ),
    ]
