# Generated by Django 3.0.5 on 2020-05-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0002_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
