# Generated by Django 3.0.5 on 2020-05-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0003_auto_20200521_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='community',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
    ]
