# Generated by Django 3.0.5 on 2020-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0003_auto_20200603_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='test',
            field=models.CharField(blank=True, default='wow', max_length=10000),
        ),
    ]
