# Generated by Django 3.0.5 on 2020-05-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0004_auto_20200521_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
