# Generated by Django 3.0.5 on 2020-06-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0004_point_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='test',
        ),
        migrations.AddField(
            model_name='point',
            name='access_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='epoch',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='point',
            name='refresh_token',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
