# Generated by Django 3.0.5 on 2020-05-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0005_account_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='password',
        ),
    ]
