# Generated by Django 3.0.7 on 2020-06-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0005_auto_20200606_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_community_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='point',
            name='community_code',
            field=models.CharField(default=1233, max_length=100),
            preserve_default=False,
        ),
    ]
