# Generated by Django 3.0.7 on 2020-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0007_auto_20200606_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_community_code',
            name='generated_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='community_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
