# Generated by Django 3.0.7 on 2020-06-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0008_auto_20200606_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_community_code',
            name='generated_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='community_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
