# Generated by Django 3.0.7 on 2020-06-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0009_auto_20200606_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='athlete_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
