# Generated by Django 3.0.7 on 2020-06-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0010_point_athlete_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='athlete_id',
            field=models.CharField(blank=True, error_messages={'unique': 'Cannot use the same strava for muliple accounts'}, max_length=100, null=True, unique=True),
        ),
    ]
