# Generated by Django 3.0.5 on 2020-05-23 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucks', '0011_auto_20200522_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
