# Generated by Django 3.0.7 on 2020-06-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0011_auto_20200606_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='athlete_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
