# Generated by Django 3.0.5 on 2020-05-23 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucks', '0012_auto_20200523_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='community',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='miles',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000, null=True),
        ),
    ]
