# Generated by Django 3.0.7 on 2020-06-18 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartCount', models.IntegerField()),
                ('cartItem1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart1', to='store.StorePost')),
                ('cartItem2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart2', to='store.StorePost')),
                ('cartItem3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart3', to='store.StorePost')),
                ('cartItem4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart4', to='store.StorePost')),
                ('cartItem5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart5', to='store.StorePost')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, unique=None)),
            ],
        ),
    ]
