# Generated by Django 3.0.7 on 2020-06-18 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20200618_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartItem1', models.CharField(blank=True, max_length=100, null=True)),
                ('cartItem2', models.CharField(blank=True, max_length=100, null=True)),
                ('cartItem3', models.CharField(blank=True, max_length=100, null=True)),
                ('cartItem4', models.CharField(blank=True, max_length=100, null=True)),
                ('cartItem5', models.CharField(blank=True, max_length=100, null=True)),
                ('orderNum', models.IntegerField(blank=True, default=0, null=True)),
                ('orderTotal', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL, unique=None)),
            ],
        ),
    ]
