# Generated by Django 3.0.7 on 2020-06-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cartItem1',
            new_name='item1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cartItem2',
            new_name='item2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cartItem3',
            new_name='item3',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cartItem4',
            new_name='item4',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='cartItem5',
            new_name='item5',
        ),
    ]
